source "http://rubygems.org"
gem 'jekyll', '~> 0.12.0'
gem 'haml'
gem 'rubypants'
gem 'stringex'
gem 'compass'
gem 'rack'
gem 'rake'
gem 'sinatra'
gem 'rdiscount'
gem 'pygments.rb'
gem 'RedCloth'
gem 'rb-fsevent'
gem 'liquid'
gem 'tilt', '~> 1.4.1'
